# Generated by Django 5.0 on 2024-01-10 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.CharField(db_index=True, max_length=10, unique=True)),
                ('name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('description', models.TextField(default='', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.CharField(db_index=True, max_length=10, unique=True)),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('description', models.TextField(default='', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Producer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.CharField(db_index=True, max_length=10, unique=True)),
                ('name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('alias', models.CharField(max_length=100, null=True)),
                ('rating', models.IntegerField(null=True)),
                ('description', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.CharField(db_index=True, max_length=10, unique=True)),
                ('name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('description', models.TextField(default='', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Torrent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash', models.CharField(db_index=True, max_length=100, unique=True)),
                ('filename', models.CharField(max_length=100, null=True)),
                ('name', models.CharField(max_length=100, null=True)),
                ('number', models.IntegerField(null=True)),
                ('size', models.IntegerField(null=True)),
                ('published_at', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.CharField(db_index=True, default='', max_length=10, unique=True)),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('gender', models.IntegerField(default=2, null=True)),
                ('age', models.IntegerField(default=0, null=True)),
                ('avatar', models.CharField(max_length=200, null=True)),
                ('birthday', models.DateField(null=True)),
                ('height', models.IntegerField(null=True)),
                ('weight', models.IntegerField(null=True)),
                ('cups', models.CharField(max_length=5, null=True)),
                ('bust', models.IntegerField(null=True)),
                ('waist', models.IntegerField(null=True)),
                ('hip', models.IntegerField(null=True)),
                ('homeland', models.CharField(max_length=100, null=True)),
                ('hobbies', models.CharField(max_length=100, null=True)),
                ('rating', models.IntegerField(null=True)),
                ('refreshed_at', models.DateTimeField(null=True)),
                ('status', models.IntegerField(default=0, null=True)),
                ('description', models.TextField(default='', null=True)),
                ('current', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous', to='core.actor')),
            ],
        ),
        migrations.CreateModel(
            name='ActorsMovies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.actor')),
            ],
        ),
        migrations.CreateModel(
            name='GenresMovies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.genre')),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('code', models.CharField(db_index=True, max_length=10, unique=True)),
                ('code_prefix', models.CharField(max_length=10, null=True)),
                ('code_number', models.CharField(max_length=10, null=True)),
                ('gid', models.IntegerField(null=True)),
                ('thumbnail', models.CharField(max_length=100, null=True)),
                ('cover', models.CharField(max_length=100, null=True)),
                ('length', models.IntegerField(null=True)),
                ('published_on', models.DateField(null=True)),
                ('rating', models.IntegerField(default=0, null=True)),
                ('refreshed_at', models.DateTimeField(null=True)),
                ('description', models.TextField(default='', null=True)),
                ('actors', models.ManyToManyField(through='core.ActorsMovies', to='core.actor')),
                ('director', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movies', to='core.director')),
                ('genres', models.ManyToManyField(through='core.GenresMovies', to='core.genre')),
                ('producer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movies', to='core.producer')),
            ],
        ),
        migrations.CreateModel(
            name='Magnet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=100, null=True)),
                ('hash', models.CharField(max_length=100, null=True)),
                ('size', models.IntegerField(null=True)),
                ('language', models.CharField(max_length=100, null=True)),
                ('definition', models.CharField(max_length=100, null=True)),
                ('shared_on', models.DateField(null=True)),
                ('movie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='magnets', to='core.movie')),
            ],
        ),
        migrations.AddField(
            model_name='genresmovies',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.movie'),
        ),
        migrations.AddField(
            model_name='genre',
            name='movies',
            field=models.ManyToManyField(through='core.GenresMovies', to='core.movie'),
        ),
        migrations.AddField(
            model_name='actorsmovies',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.movie'),
        ),
        migrations.AddField(
            model_name='actor',
            name='movies',
            field=models.ManyToManyField(through='core.ActorsMovies', to='core.movie'),
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.CharField(db_index=True, max_length=10, unique=True)),
                ('name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('alias', models.CharField(max_length=100, null=True)),
                ('rating', models.IntegerField(null=True)),
                ('description', models.TextField(null=True)),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='core.publisher')),
            ],
        ),
        migrations.AddField(
            model_name='movie',
            name='publisher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movies', to='core.publisher'),
        ),
        migrations.AddField(
            model_name='movie',
            name='series',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movies', to='core.series'),
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('path', models.CharField(max_length=100)),
                ('md5', models.CharField(max_length=100, null=True)),
                ('codec', models.CharField(max_length=100, null=True)),
                ('width', models.IntegerField(default=0)),
                ('height', models.IntegerField(default=0)),
                ('duration', models.FloatField(default=0)),
                ('size', models.IntegerField(default=0)),
                ('bit_rate', models.IntegerField(default=0)),
                ('movie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='videos', to='core.movie')),
            ],
        ),
    ]
