# Generated by Django 5.0 on 2024-01-12 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='definition',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
