# Generated by Django 5.0 on 2024-01-18 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_video_definition'),
    ]

    operations = [
        migrations.AddField(
            model_name='magnet',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
