# Generated by Django 5.0 on 2024-01-20 02:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_magnet_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='magnet',
            name='torrent',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.torrent'),
        ),
    ]
