# Generated by Django 5.0 on 2024-01-20 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_magnet_torrent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='torrent',
            name='created_at',
        ),
        migrations.AddField(
            model_name='torrent',
            name='created_on',
            field=models.DateField(null=True),
        ),
    ]
